2014/12/08 18:04:13 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Server 127.0.0.1 (tcp 11211) failed with: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:33
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (33)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:04:13 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Can't connect to 127.0.0.1:11211, 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:33
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (33)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:04:14 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Server 127.0.0.1 (tcp 11211) failed with: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:34
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (34)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:04:14 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Can't connect to 127.0.0.1:11211, 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:34
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (34)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:04:14 [error] [application] 系统错误:Memcache::set() [<a href='memcache.set'>memcache.set</a>]: No servers added to memcache connection->file:D:\wwwroot\veecar\framework\core\Cache.php->line:46
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
in D:\wwwroot\veecar\protected\controllers\IndexController.php (17)
2014/12/08 18:17:49 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Server 127.0.0.1 (tcp 11211) failed with: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:33
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (33)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:17:49 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Can't connect to 127.0.0.1:11211, 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:33
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (33)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:17:50 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Server 127.0.0.1 (tcp 11211) failed with: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:34
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (34)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:17:50 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Can't connect to 127.0.0.1:11211, 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:34
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (34)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:17:50 [error] [application] 系统错误:Memcache::set() [<a href='memcache.set'>memcache.set</a>]: No servers added to memcache connection->file:D:\wwwroot\veecar\framework\core\Cache.php->line:46
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
in D:\wwwroot\veecar\protected\controllers\IndexController.php (17)
2014/12/08 18:17:55 [error] [application] 系统错误:Use of undefined constant IVY_DEBUG - assumed 'IVY_DEBUG'->file:D:\wwwroot\veecar\framework\core\CException.php->line:88
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\CException.php (88)
2014/12/08 18:18:00 [error] [application] 系统错误:Use of undefined constant IVY_DEBUG - assumed 'IVY_DEBUG'->file:D:\wwwroot\veecar\framework\core\CException.php->line:88
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\CException.php (88)
2014/12/08 18:18:28 [error] [application] 
 <!--Fatal error-->:  未捕获的异常Ivy\core\CException  
异常消息：default-分组不存在！  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:130  
function:dispatch  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 
  Ivy\core\Route::__set_state(array(
     'route' => 
    array (
      'module' => 'default',
      'controller' => 'index',
      'action' => 'index',
    ),
  )),
)  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:93  
function:dispatch  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 
  Ivy\core\Route::__set_state(array(
     'route' => 
    array (
      'module' => 'default',
      'controller' => 'index',
      'action' => 'index',
    ),
  )),
  1 => 
  array (
    'name' => '我被覆盖了',
  ),
)  
file:D:\wwwroot\veecar\protected\views\index\view.phtml  
line:9  
function:widget  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 'default/index',
  1 => 
  array (
    'name' => '我被覆盖了',
  ),
)  
file:D:\wwwroot\veecar\framework\core\Template.php  
line:27  
args:array (
  0 => 'D:\\wwwroot\\veecar\\protected\\views\\index\\view.phtml',
)  
function:include_once  
file:D:\wwwroot\veecar\protected\controllers\IndexController.php  
line:42  
function:display  
class:Ivy\core\Template  
type:->  
args:array (
)  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:148  
function:viewAction  
class:IndexController  
type:->  
args:array (
)  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:104  
function:dispatch  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 
  Ivy\core\Route::__set_state(array(
     'route' => 
    array (
      'controller' => 'index',
      'action' => 'view',
    ),
  )),
)  
file:D:\wwwroot\veecar\index.php  
line:7  
function:run  
class:Ivy\core\Application  
type:->  
args:array (
)  
异常抛出点：D:\wwwroot\veecar\framework\core\Application.php on line 139

2014/12/08 18:18:49 [error] [application] 
 <!--Fatal error-->:  未捕获的异常Ivy\core\CException  
异常消息：default-分组不存在！  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:130  
function:dispatch  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 
  Ivy\core\Route::__set_state(array(
     'route' => 
    array (
      'module' => 'default',
      'controller' => 'index',
      'action' => 'index',
    ),
  )),
)  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:93  
function:dispatch  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 
  Ivy\core\Route::__set_state(array(
     'route' => 
    array (
      'module' => 'default',
      'controller' => 'index',
      'action' => 'index',
    ),
  )),
  1 => 
  array (
    'name' => '我被覆盖了',
  ),
)  
file:D:\wwwroot\veecar\protected\views\index\view.phtml  
line:9  
function:widget  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 'default/index',
  1 => 
  array (
    'name' => '我被覆盖了',
  ),
)  
file:D:\wwwroot\veecar\framework\core\Template.php  
line:27  
args:array (
  0 => 'D:\\wwwroot\\veecar\\protected\\views\\index\\view.phtml',
)  
function:include_once  
file:D:\wwwroot\veecar\protected\controllers\IndexController.php  
line:42  
function:display  
class:Ivy\core\Template  
type:->  
args:array (
)  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:148  
function:viewAction  
class:IndexController  
type:->  
args:array (
)  
file:D:\wwwroot\veecar\framework\core\Application.php  
line:104  
function:dispatch  
class:Ivy\core\Application  
type:->  
args:array (
  0 => 
  Ivy\core\Route::__set_state(array(
     'route' => 
    array (
      'controller' => 'index',
      'action' => 'view',
    ),
  )),
)  
file:D:\wwwroot\veecar\index.php  
line:7  
function:run  
class:Ivy\core\Application  
type:->  
args:array (
)  
异常抛出点：D:\wwwroot\veecar\framework\core\Application.php on line 139

2014/12/08 18:37:43 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Server 127.0.0.1 (tcp 11211) failed with: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:33
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (33)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:37:43 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Can't connect to 127.0.0.1:11211, 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:33
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (33)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:37:44 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Server 127.0.0.1 (tcp 11211) failed with: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:34
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (34)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:37:44 [error] [application] 系统错误:Memcache::connect() [<a href='memcache.connect'>memcache.connect</a>]: Can't connect to 127.0.0.1:11211, 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
 (10060)->file:D:\wwwroot\veecar\framework\core\Cache.php->line:34
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (34)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
2014/12/08 18:37:44 [error] [application] 系统错误:Memcache::set() [<a href='memcache.set'>memcache.set</a>]: No servers added to memcache connection->file:D:\wwwroot\veecar\framework\core\Cache.php->line:46
in D:\wwwroot\veecar\framework\core\CException.php (42)
in D:\wwwroot\veecar\framework\core\Cache.php (46)
in D:\wwwroot\veecar\protected\controllers\IndexController.php (17)
